# Gemini transcription service - handles speech-to-text transcription using Google Gemini
import time
import logging
import io
from typing import Dict, List, Optional

from app.config import settings

logger = logging.getLogger(__name__)


def transcribe_audio_gemini(audio_path: str) -> Dict:
    """
    Transcribe audio using Google Gemini.

    Args:
        audio_path: Path to the audio file

    Returns:
        Dictionary containing transcription result with segments
    """
    try:
        import google.generativeai as genai

        # Configure Gemini client
        genai.configure(api_key=settings.GEMINI_API_KEY)

        # Load audio file
        with open(audio_path, "rb") as audio_file:
            audio_data = audio_file.read()

        # Create a Gemini model for transcription
        model = genai.GenerativeModel(
            model_name=settings.GEMINI_MODEL,
            generation_config={
                "temperature": 0.1,
                "max_output_tokens": 8192,
                "response_mime_type": "application/json",
                "response_schema": {
                    "type": "object",
                    "properties": {
                        "language": {"type": "string"},
                        "segments": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "text": {"type": "string"},
                                    "start": {"type": "number", "description": "Start time in total seconds as a float (e.g. 60.5 for 1m0.5s)"},
                                    "end": {"type": "number", "description": "End time in total seconds as a float (e.g. 63.2 for 1m3.2s)"}
                                },
                                "required": ["text", "start", "end"]
                            }
                        }
                    },
                    "required": ["language", "segments"]
                }
            },
        )

        # Create prompt for transcription
        prompt = """
        You are an audio transcription assistant. Transcribe the following audio file.
        Return the transcription as a JSON object matching the required schema.

        Note: Since this is a transcription task, please provide the actual transcribed text
        and reasonable timestamps for each segment in total seconds. Do NOT include speaker information.
        CRITICAL: The "start" and "end" timestamps MUST be valid floating point values in total seconds (e.g., 60.5 for 1 minute and 0.5 seconds). DO NOT use formatted strings or multiple decimals like 1.0.66.
        """

        logger.info("Uploading audio file to Gemini: %s", audio_path)
        # Upload the audio file to Gemini
        audio_file_obj = genai.upload_file(path=audio_path)

        logger.info("Generating transcription with Gemini for audio: %s", audio_path)
        # Generate the transcription
        response = model.generate_content([prompt, audio_file_obj])

        import json
        # Parse the JSON response
        try:
            result = json.loads(response.text)
            
            # Print the transcription generated by Gemini
            logger.info("Gemini Transcription Output: %s", json.dumps(result, indent=2))
            
            # Ensure the segments don't have speaker fields to prevent interference with our own diarization
            if "segments" in result:
                for segment in result["segments"]:
                    if "speaker" in segment:
                        del segment["speaker"]
            
            # Delete the file from Gemini to save space
            genai.delete_file(audio_file_obj.name)
            
            return result
        except json.JSONDecodeError as e:
            logger.error("Failed to parse Gemini response as JSON: %s\nResponse: %s", str(e), response.text)
            genai.delete_file(audio_file_obj.name)
            raise

    except Exception as e:
        logger.error("Gemini transcription failed: %s", str(e))
        raise


def get_gemini_device_config():
    """
    Get device configuration for Gemini (CPU only, as Gemini runs in the cloud).

    Returns:
        Dictionary with device configuration
    """
    return {
        "device": "cpu",
        "compute_type": "float32",
        "batch_size": 1,
    }


def cleanup_gemini_resources():
    """
    Cleanup Gemini resources (no GPU memory to free for cloud-based Gemini).
    """
    logger.info("Gemini cleanup - no local resources to free")
